### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Xu-Qingpo** [luwis93choi/Deep_3D_LiDAR_VO#1]
Thanks for your work.
 Can you provide other links to the database? The database you provided cannot be accessed.

**Comment by luwis93choi** [comment]
I used official KITTI visual odometry dataset from the following link.
[KITTI Visual Odometry Dataset](https://www.cvlibs.net/datasets/kitti/eval_odometry.php)

**Comment by Xu-Qingpo** [comment]
Thank you for your reply. I'm new to this, can you tell me how to put the kitti dataset to apply this work?
 Furthermore, via "python main.py --/media/xx/dataset/KITTI-Odometry/sequences --/media/xx/dataset/KITTI-Odometry/data_odometry_color/dataset/sequences --/media/xx/dataset/KITTI-Odometry /data_odometry_poses/dataset/poses --0 --1 --./1620221072.933818/CRNN_VO_model.pth" right?
This pre_trained_network seems to have no files.
